### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nimaa77** [jaredpalmer/after.js#281]
This issue is a high-level roadmap for all work for the next releases. 

This list is by no means exhaustive and will change from time to time as new issues are opened and PRs are merged.

### 1.6
- [ ] Enable Tree Shaking
- [ ] Create After App
- [ ] Auto Scroll Control

### 2
- [ ] No warnings in React 16's <StrictMode>
  - [ ]  Remove all usage of componentWill* methods
  - [ ]  Fix React Helmet Strict Mode warnings 

### 2.1
- [ ] Nested Routes (react-router-config)
- [ ] Render Async (ReactDOM.renderToNodeStream)

### Backlog
- [ ] Fix Typescript type errors
- [ ] Add Examples
